### PR TITLE
Adding bundler support

### PR DESCRIPTION
**Pull request by martinos**
I have added bundler support for the gem.

This way it's easier for contributer to setup their test environment:

### CODE REVIEW

**Comment by cldwalker** [comment]
Why do this when anyone can install development dependencies with gem install boson --dev?

**Comment by martinos** [comment]
Because, gemspecs are loose dependencies.  When you do a gem install, rubygems tries to find in your local repository the most recent versions of gems that matches the gemspecs. If it does not find the gems it will install them to your machine with the most recent recent that matches the gemspecs. The problem with that approach is that the contributer will probably have a different gem set than the maintainer. Gemfile.lock is a manifest that says that the gem was tested against a precise gem setup.

The other advantage of developing in bundler is that it isolate your app in its own sandboxes.  It ensures that your gemspec has all the proper gem dependency  and that the developer hasn't forgotten some gem dependecies (which happens quite often).

**Comment by martinos** [comment]
If you want to have more details about this method:
http://jeffkreeftmeijer.com/2010/be-awesome-write-your-gemspec-yourself/
https://github.com/radar/guides/blob/master/gem-development.md

As you will notice this method adds three rake helper tasks to simplify gem publishing:

rake build    # Build gemtemplate-0.0.1.gem into the pkg directory
rake install  # Build and install gemtemplate-0.0.1.gem into system gems
rake release  # Create tag v0.0.1 and build and push gemtemplate-0.0.1.gem to Rubygems

gemtemplate is the gem name.

**Comment by cldwalker** [comment]
bundler is great for webapps where dependencies of dependencies may conflict but it is overkill for boson which has none of these issues. If you're worried about sandboxing, use rvm or rip. Philosophy, I disagree with adding any unnecessary dependencies in a Rakefile (which bundler would be). When I come to contribute to a project, I find it annoying when a gem requires that I install their latest, favorite development tools. If you look across my projects, I consistently keep this philosophy.

As for the rake tasks, boson already has a rake install and rake gem is the same as rake build. rake release seems pointless for boson's case ( I don't have others releasing for me).

I appreciate the commit but it's nothing that can't already be done with your own sandboxing and the above gem install.

**Comment by martinos** [comment]
I agree that it might be overkill. I was just sending to you this is case you where interested in it.

**Comment by cldwalker** [comment]
Appreciate the suggestion but opposed to it for practical and philosophical reasons.

**Pull request closed without merging**
