### PR TITLE
Adding File#lock around index.marshal file

### PR DESCRIPTION
**Pull request by martinos**
I have ran into an issue where concurrent processes were writing to the index at the same time.  This had the effect of corrupting it. 

I had the following error:
Error: marshal data too short

Since I have made the modification I did not have any issues.

### CODE REVIEW

**Comment by cldwalker** [comment]
Generally I'd like to see tests with a pull request but given that boson's test suite is a mess and I'm moving onto boson2, I don't mind so much. Fyi, boson2 will basically be a 1.9 only slimmer version. I'll put more details in the readme.

**Comment by cldwalker** [comment]
I can pull once I get some answers to the above questions

**Comment by martinos** [comment]
Normally I write tests, in this case I did't know how to test it.

**Comment by cldwalker** [comment]
I was going to pull this in but noticed most of the tests are failing with: `No such file test/config/index.marshal`. When I did add an empty file it errors with `end of file too short`. If you'd like this pulled in I'll need passing tests.

**Comment by martinos** [comment]
I was pretty sure that I ran the tests and they passed, but I re-ran them and they failed. I am getting a look at it and I will fix it.

**Comment by cldwalker** [comment]
I'm only seeing that test failure with mocha 0.10.2 but mocha 0.9.8 works. I'd stick with what works for now.

**Comment by martinos** [comment]
Hello Sir, 
Sorry for the long delay, I was pretty busy down here.  I have made a correction to the source code. Now all test are passing and it's running well in production.

Now I am opening the file in File::RDWR, File::CREAT and binary mode.  This way the file is created if it's not already existing, which was not the case with my other patch.

**Comment by cldwalker** [comment]
No worries. I've merged and am releasing now.

**Pull request closed without merging**
